Story_7/urls.py
from django.urls import path

from . import views

app_name = 'history'

urlpatterns = [
    path('', views.displayHistory, name='display-history'),
    path('create-accordion', views.formHistory, name='create-accordion'),
    path('create-accordion-dropdown', views.formListHistory, name='create-accordion-dropdown'),
]

Story_8/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.searchBooks, name='search-books'),
    path('data/', views.data),
]

Story_9/urls.py
from django.urls import path

from .views import SignUp, SignIn, LogOut

app_name = 'user'

urlpatterns = [
    path('signup/', SignUp, name='signup'),
    path('logout/', LogOut, name='logout'),
    path('signin/', SignIn, name='signin'),
]

lastppw2020/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('history/', include('Story_7.urls', namespace='history')),
    path('search/', include('Story_8.urls', namespace='search')),
    path('user/', include('Story_9.urls', namespace='user'))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

Story_7/models.py
from django.db import models

# Create your models here.

class History(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class listHistory(models.Model):
    name = models.CharField(max_length=100)
    history = models.ForeignKey(History, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Story_8/models.py
from django.db import models

# Create your models here.

Story_9/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

Story_7/forms.py
from django import forms
from .models import listHistory,History

class history(forms.ModelForm):
    class Meta:
        model = History
        fields = {
            'name',
        }

        labels = {
            'name': 'Nama Accordion',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #E4E4E4;',
                                             'placeholder': 'ex: Pacar Saya...', }),
        }

class listhistory(forms.ModelForm):
    class Meta:
        model = listHistory
        fields = {
            'name',
            'history',
        }

        labels = {
            'name': 'List Dropdown',
            'history' : 'Accordion'
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #E4E4E4;',
                                           'placeholder': 'ex: Pacar Saya...', }),
            'history' : forms.Select(attrs={'class' : 'form-control', 'style': 'background-color: #E4E4E4;',})
        }

Story_7/views.py
from django.shortcuts import render, redirect
from .models import listHistory, History
from .forms import listhistory, history

# Create your views here.

def displayHistory(request):
    listhistory = listHistory.objects.all()
    history = History.objects.all()
    context = {
        'listhistory' : listhistory,
        'history' : history,
    }
    return render(request, 'Story_7/display_history.html', context)

def formHistory(request):
    form_history = history(request.POST or None)
    context = {
        'form_history' : form_history,
    }
    if request.user.is_authenticated:
        if request.method == 'POST':
            if form_history.is_valid():
                form_history.save()
                return redirect('history:display-history')
        return render(request, 'Story_7/create_accordion.html', context)
    else:
        return redirect('history:display-history')

def formListHistory(request):
    form_listhistory = listhistory(request.POST or None)
    context = {
        'form_listhistory' : form_listhistory,
    }
    if request.user.is_authenticated:
        if request.method == 'POST':
            if form_listhistory.is_valid():
                form_listhistory.save()
                return redirect('history:display-history')
        return render(request, 'Story_7/create_accordion_dropdown.html', context)
    else:
        return redirect('history:display-history')

Story_8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.

def searchBooks(request):
    context = {}
    return render(request, 'Story_8/search.html', context)

def data(request):
    arg = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(url)
    context = json.loads(r.content)
    return JsonResponse(context, safe=False)

Story_9/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.
def SignUp(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.save()
        login(request, user)
        return redirect('main:home')

    return render(request, 'Story_9/signup.html')

def LogOut(request):
    if request.method == 'POST':
        boolean = request.POST['boolean']
        if boolean == "true":
            logout(request)
        return redirect('main:home')
    return render(request, 'Story_9/logout.html')

def SignIn(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, "Nama atau password yang anda masukkan salah")
    return render(request, 'Story_9/signin.html')

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'main/home.html')

Story_7/templates/Story_7/create_accordion.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Buat Accordion</title>
    <link rel="stylesheet" href="{% static 'css/style_Story_7.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    <div class="container">
        <div style="text-align: center">
            <h2>Buat Accordion</h2>
        </div>
       <form method="post" class="form-group" enctype="multipart/form-data">
           {{ form_history.media }}
           {% csrf_token %}
           <div class="form-group row">
               <label for="{{ form_history.name.id_for_label }}" class="col-sm-2 col-form-label">Accordion:</label>
               <div class="col-sm-10">
                   {{ form_history.name }}
               </div>
           </div>

           <div style="text-align: center">
               <button class= "btn btn-primary" type="submit" style="margin-top: 20px">Submit</button>
           </div>
       </form>
    </div>
{% endblock content %}

Story_7/templates/Story_7/create_accordion_dropdown.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Buat Isi Accordion</title>
    <link rel="stylesheet" href="{% static 'css/style_Story_7.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    <div class="container">
        <div style="text-align: center">
            <h2>Buat Isi Accordion</h2>
        </div>
       <form method="post" class="form-group" enctype="multipart/form-data">
           {{ form_listhistory.media }}
           {% csrf_token %}
           <div class="form-group row">
               <label for="{{ form_listhistory.name.id_for_label }}" class="col-sm-2 col-form-label">List Dropdown:</label>
               <div class="col-sm-10">
                   {{ form_listhistory.name }}
               </div>
           </div>
           <div class="form-group row">
               <label for="{{ form_listhistory.history.id_for_label }}" class="col-sm-2 col-form-label">Accordion:</label>
               <div class="col-sm-10">
                   {{ form_listhistory.history }}
               </div>
           </div>
           <div style="text-align: center">
               <button class= "btn btn-primary" type="submit" style="margin-top: 20px">Submit</button>
           </div>
       </form>
    </div>
{% endblock content %}

Story_7/templates/Story_7/display_history.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Tentang Saya</title>
    <link rel="stylesheet" href="{% static 'css/style_Story_7.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    <div class="container">
        <div style="text-align: center">
            <h2>Tentang saya</h2>
        </div>
        <div class="flex">
            {% if history != 0 %}
                <div class="accordion">
                    {% for histo in history %}
                    <div class="contentslide">
                        <div class="label">
                            <div class="row">
                                <div class="col-6">
                                    <p style="color: whitesmoke;">{{ histo.name }}</p>
                                </div>
                                <div class="col-2">
                                    <button type="button" class="btn btn-primary btn-slider">+</button>
                                </div>
                                <div class="col-2">
                                    <button type="button" class="btn btn-primary btn-up" style="background-color: #fe6a60; border-color: #fe6a60;">^</button>
                                </div>
                                <div class="col-2">
                                    <button type="button" class="btn btn-primary btn-down" style="background-color: #fe6a60; border-color: #fe6a60;">V</button>
                                </div>
                            </div>
                        </div>
                        <div class="content">
                            <ul>
                            {% for list in listhistory %}
                                {% if list.history.name == histo.name %}
                                        <li>{{ list.name }}</li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <h3>KOSONG</h3>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
            <div style="text-align: center">
                <a href="{% url 'history:create-accordion' %}"><button class= "btn btn-primary" style="margin-top: 20px">Tambah Accoridon</button></a>
                <a href="{% url 'history:create-accordion-dropdown' %}"><button class= "btn btn-primary" style="margin-top: 20px">Tambah Konten</button></a>
            </div>
        {% endif %}
    </div>
    <script src="{% static 'js/slider.js' %}"></script>
{% endblock content %}

Story_8/templates/Story_8/search.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Search Books</title>
    <link rel="stylesheet" href="{% static 'css/style-Story8.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    <div class="container">
        <div>
            <h3 style="text-align: center">Pencarian Buku</h3>
            <input class="form-control"  id="keyword" placeholder="Masukkan judul Buku">
        </div>
        <div class="accordion">
        </div>
    </div>

    <script src="{% static 'js/search.js' %}"></script>
{% endblock content %}

Story_9/templates/Story_9/logout.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log Out</title>
{% endblock meta %}

{% block content %}
  <div class="container">
    <p style="text-align: center">Apkah anda ingin logout</p>
    <form method="post">
        {% csrf_token %}
        <div style="text-align: center">
            <button class= "btn btn-primary" name='boolean' type="submit" value="true" style="margin-top: 20px">Ya</button>
            <button class= "btn btn-primary" name='boolean' type="submit" value="false" style="margin-top: 20px">Tidak</button>
        </div>
    </form>
  </div>
{% endblock content %}

Story_9/templates/Story_9/signin.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign Up</title>
{% endblock meta %}

{% block content %}
    <div class="container">
        <h3 style="text-align: center">LOG IN</h3>
        <form method="post" class="form-group" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-2 col-form-label">Username</label>
                <div class="col-10">
                    <input type="text" name="username" class="form-control" id="username">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-2 col-form-label">Password</label>
                <div class="col-10">
                    <input type="password" name="password" class="form-control" id="password">
                </div>
            </div>
            <div style="text-align: center">
               <button class= "btn btn-primary" type="submit" style="margin-top: 20px">Log In</button>
           </div>
        </form>
    </div>
{% endblock content %}

Story_9/templates/Story_9/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign Up</title>
{% endblock meta %}

{% block content %}
    <div class="container">
        <h3 style="text-align: center">DAFTARKAN DIRI ANDA</h3>
        <form method="post" class="form-group" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-2 col-form-label">Username</label>
                <div class="col-10">
                    <input type="text" name="username" class="form-control" id="username">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-2 col-form-label">Email</label>
                <div class="col-10">
                    <input type="email" name="email" class="form-control" id="emailUser">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-2 col-form-label">Password</label>
                <div class="col-10">
                    <input type="password" name="password" class="form-control" id="password">
                </div>
            </div>
            <div style="text-align: center">
               <button class= "btn btn-primary" type="submit" style="margin-top: 20px">Daftar</button>
           </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello</title>
{% endblock meta %}

{% block content %}
  <h1>Hello</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {%  if user.is_authenticated %}
            <a class="navbar-brand">Hello {{ user.get_username }}</a>
        {% else %}
            <a class="navbar-brand">Hello</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'history:display-history' %}">My History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:search-books' %}">Search</a>
                </li>
            </ul>
            <ul class="navbar-nav navbar-right">
                {% if user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:signin' %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
  {% block content %}
  {% endblock content %}
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>